services:
  - type: web
    name: aditya-portfolio
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn Web.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
